# Generated by Django 5.2.6 on 2026-09-27 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidatos", "0002_candidato_genero"),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidatoFoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archivo",
                    models.ImageField(
                        blank=True, null=True, upload_to="candidatos/%Y/%m/"
                    ),
                ),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "alt",
                    models.CharField(
                        blank=True,
                        help_text="Qué se ve en la foto, para quien usa lector de pantalla.",
                        max_length=200,
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "candidato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fotos",
                        to="candidatos.candidato",
                    ),
                ),
            ],
            options={
                "verbose_name": "Foto de candidato",
                "verbose_name_plural": "Fotos de candidatos",
                "ordering": ["orden", "id"],
            },
        ),
    ]
