# Generated by Django 5.2.6 on 2026-09-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Colaboracion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("voluntario", "Voluntariado"),
                            ("transito", "Hogar de tránsito"),
                        ],
                        max_length=20,
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "disponibilidad",
                    models.CharField(
                        blank=True,
                        help_text="Qué días o en qué horarios puede colaborar.",
                        max_length=200,
                    ),
                ),
                ("mensaje", models.TextField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("nueva", "Nueva"),
                            ("contactada", "Contactada"),
                            ("aceptada", "Aceptada"),
                            ("archivada", "Archivada"),
                        ],
                        default="nueva",
                        max_length=20,
                    ),
                ),
                (
                    "nota_interna",
                    models.TextField(
                        blank=True,
                        help_text="Notas del equipo, no las ve quien se postula.",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Colaboración",
                "verbose_name_plural": "Colaboraciones",
                "ordering": ["-fecha_creacion"],
            },
        ),
    ]
