# Generated by Django 5.0.1 on 2025-11-27 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidatos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visita', models.DateTimeField()),
                ('visitante_nombre', models.CharField(max_length=100)),
                ('visitante_email', models.EmailField(max_length=254)),
                ('visitante_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(choices=[('planificada', 'Planificada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada')], default='planificada', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='candidatos.candidato')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'ordering': ['fecha_visita'],
            },
        ),
    ]
