# Generated by Django 5.0.1 on 2025-11-27 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='comentario_final',
            field=models.TextField(blank=True, null=True, verbose_name='Comentario Final'),
        ),
    ]
