# Generated by Django 5.2.6 on 2026-09-27 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visitas", "0003_solicitudvisita"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitudvisita",
            name="visita",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="solicitud",
                to="visitas.visita",
            ),
        ),
        migrations.AddField(
            model_name="visita",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="visitas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
